### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by AYastrebov** [ivlevAstef/DITranquillity#100]
I've setup a new project.
Added a dependency with Carthage.

The project is unable to build

![2017-08-11_18-59-49](https://user-images.githubusercontent.com/739037/29221387-43e16e7e-7ec7-11e7-8a59-16ad50992c64.png)

**Comment by ivlevAstef** [comment]
Oops ... I'll see, I did not check the build for a long time through cartage.

**Comment by ivlevAstef** [comment]
I fixed the problem... In the future I will consider feature of carthage.
I didn't change version of the library, but the current state of the master should be working.
