### ISSUE TITLE
Не работает register1 с injection many($1)

### ISSUE THREAD

**Issue by dmitriyborodko** [ivlevAstef/DITranquillity#112]
На валидации падает:
DI [error]: Not found component for type: () from Component with type: SettingsComponentUIService in file: SettingsDIFramework.swift on line: 30

Приходится создавать фейковый протокол Test и добавлять .as(check: Test.self) {$0} , что бы работало с register без единички.

**Comment by ivlevAstef** [comment]
Так зачем ты ему ноль параметров на вход суешь, если функция называется register1 ? :)
