### ISSUE TITLE
Integrated with SourceKittenFramework

### ISSUE THREAD

**Issue by ivlevAstef** [ivlevAstef/DITranquillity#119]
https://github.com/jpsim/SourceKitten/tree/master/Source/SourceKittenFramework

Library can get AST, can wrote warnings/errors dyring build.

But it's hard...

**Comment by ivlevAstef** [comment]
https://github.com/Nekitosss/DITranquillityLinter

**Comment by dehrom** [comment]
Soo what? 🙃 many years have passed

**Comment by ivlevAstef** [comment]
No... :( There will be no forces for such a complex integration.

But after 4.5.0 version I added root components. Under certain conditions, this gives stricter checks. https://github.com/ivlevAstef/DITranquillity/blob/master/Documentation/ru/core/registration_and_service.md#%D1%80%D1%83%D1%82%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82
