### ISSUE TITLE
I can not build a static library

### ISSUE THREAD

**Issue by mefilt** [ivlevAstef/DITranquillity#122]
Hello. I use cocoapod. I can not build a static library.
<img width="1120" alt="2018-05-27 3 10 54" src="https://user-images.githubusercontent.com/1247906/40581257-d449897a-615b-11e8-95ac-137d4f843f0d.png">

**Comment by ivlevAstef** [comment]
Thank you for using the library. Yes, I did not check for static compilation using cocoapods.

On Monday I will correct - it is not difficult

**Comment by mefilt** [comment]
Thx and Спасибо 👍

**Comment by ivlevAstef** [comment]
fix in version 3.3.6 (and SwiftLazy 1.0.2)

**Comment by mefilt** [comment]
You need remove Bridging-Header from project. 

<img width="1019" alt="2018-05-29 0 27 40" src="https://user-images.githubusercontent.com/1247906/40629973-60ab92ec-62d7-11e8-8de1-6096b7f48d0c.png">

**Comment by mefilt** [comment]
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '#######' do
  # # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  #
  # # Pods for ####

  # Network
  pod 'Moya', '~> 11.0'
  pod 'Moya/RxSwift', '~> 11.0'

  # RX
  pod 'RxSwift'

  # Map
  pod 'YandexMapKit', '~> 3.0.0'

  # DI
  pod 'DITranquillity'

  # Auto Generate Code
  pod 'SwiftGen'
end

**Comment by ivlevAstef** [comment]
Sorry. This worked for cocoapods 1.4.x.
Push version `3.3.7` for cocoapods 1.5.x.
Thanks for waiting.
