### ISSUE TITLE
Register with init without parameters after update to v3.7.1

### ISSUE THREAD

**Issue by Anavrin1990** [ivlevAstef/DITranquillity#139]
This form of register doesn't work for classes with init without parameters only this form container.register{ClassName()}

![image](https://user-images.githubusercontent.com/25079982/58702621-b2025400-83bf-11e9-9249-27294be2168f.png)

**Comment by Anavrin1990** [comment]
No, it is work for classes with init without parameters. I don't know why it is happening

<img width="1767" alt="Снимок экрана 2019-05-31 в 16 34 49" src="https://user-images.githubusercontent.com/25079982/58703572-8765ca80-83c2-11e9-875f-1cb60b928ecb.png">

**Comment by ivlevAstef** [comment]
Please write swift version.
I check tests on swift 5.0,4.2, 4.0 and it's works.

But on version 3.x it's doen't work - I wrote about it.

If swift version 4.0 and greatest please write one full test. I cann't reproduce.

**Comment by ivlevAstef** [comment]
I found problem.
`DisposeBag` have more initialization method:
```
public override init()
public convenience init(disposing disposables: Disposable...)
public convenience init(disposing disposables: [Disposable])
```
And library can't decide
I think your viewController have two initializations:
```
init(disposebag: DisposeBag)
init(nibName:bundle:)
```

In old realizations for one parameter registers need wrote `register1` - this cut off part of the options.
But now have only `register`.

Please use other syntax;
```
container.register(ViewController.init())
container.register { ViewController() }
container.register(ViewController.init(nibName:bundle:))
container.register { ViewController(nibName: $0, bundle: $1) }
container.register(ViewController.init(disposebag:))
container.register { ViewController(disposebag: $0) } 
container.register(DisposeBag.init())
container.register { DisposeBag() }
container.register(DisposeBag.init(disposing:))
container.register { DisposeBag(disposing: $0) }
```
to specify the initialization method exactly.
or remove(or change access level to private) other initialization methods.

**Comment by Anavrin1990** [comment]
Thank you
This syntax doesn't work container.register(DisposeBag.init())
but
This work perfect container.register { DisposeBag() }
