### ISSUE TITLE
Внедрение зависимостей через свойства используя KeyPath swift 5

### ISSUE THREAD

**Issue by makleso6** [ivlevAstef/DITranquillity#140]
Спасибо за библиотеку!
в swift 5 не поддерживается внедрение зависимостей через свойства используя KeyPath если свойство private(set)

```
class AppPart: DIPart {
    static func load(container: DIContainer) {
        container.register(Presenter.init)
        container.register(ViewController.init)
            .injection(\.presenter)
    }
}
class Presenter {
}

class ViewController {
    private(set) var presenter: Presenter!
}
```

**Comment by Nekitosss** [comment]
Looks like resolved swift bug
https://bugs.swift.org/browse/SR-7448

**Comment by ivlevAstef** [comment]
Да к сожалению Apple решили, что это баг и впринципе они правы.
Но как по мне это была отличная бага позволяющая хоть что-то сделать незаконного :)

Поэтому придется удалять `private(set)` в подобных местах, и надо бы документацию проверить

**Comment by makleso6** [comment]
Спасибо)
