### ISSUE TITLE
carthage build failed

### ISSUE THREAD

**Issue by hehekta** [ivlevAstef/DITranquillity#143]
Не собирается кортежем. 

Ругается, что не может найти файл, хотя файл присутствует. В скриптах кортежа копирование фреймворков прописано. Пробовал и DITranquillity.framework, и SwiftLazy.framework - результат один и тот же.

*** Building scheme "SwiftLazy-iOS" in SwiftLazy.xcodeproj

**Failed to read file or folder at** /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/SwiftLazy/v1.1.3/Build/Intermediates.noindex/ArchiveIntermediates/SwiftLazy-iOS/BuildProductsPath/Release-iphoneos/SwiftLazy.framework

**Comment by ivlevAstef** [comment]
Эту ошибку поправил, но там возникла аналогичная на DITranquillity.
И походу единственный способ поправить ошибку это полностью заново пересоздать проект.

P.S. Возможно в версии 3.7.4 уже все хорошо, но я не успел проверить.

**Comment by hehekta** [comment]
Проект собирается, и SwiftLazy, и DITranquillity. Все отлично, спасибо большое
