### ISSUE TITLE
XCode 11 and SPM support

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [ivlevAstef/DITranquillity#148]
Hello!
I just installed last version of DITranquillity into new XCode 11 project and got error:
/Users/maxpolkovnik/Library/Developer/Xcode/DerivedData/zero-gedszlwfqazgdpdbeqtvstwqrmiw/SourcePackages/checkouts/SwiftLazy/Sources/SwiftLazy/Multithread.swift:21:12: 'SpinLock' is only available in iOS 10.0 or newer

I used latest XCode Version 11.0 (11A420a). Installed DITranquillity via File->Swift Packages->Add Package Dependency

**Comment by ivlevAstef** [comment]
Hello!
You can send file `/Users/maxpolkovnik/Library/Developer/Xcode/DerivedData/zero-gedszlwfqazgdpdbeqtvstwqrmiw/SourcePackages/checkouts/SwiftLazy/Sources/SwiftLazy/Multithread.swift`?

**Comment by ivlevAstef** [comment]
You used version 4.x.x? - need use 3.x.x. I don't know where version 4 came from.

I removed 4.x.x.
And fix swiftPM in version 3.8.4
