### ISSUE TITLE
Add UI folder to SPM Package

### ISSUE THREAD

**Issue by SpectralDragon** [ivlevAstef/DITranquillity#161]
Currently only cococapods can delivery a DIStoryboard supports in the library. Can you include UI using cross language support in SPM?

**Comment by Nekitosss** [comment]
Hello, if I remember correctly I was the one who implemented SPM. Back then there was no possibility to mix swift and objc code in the target. I believe that is still the case. 
You may give it a try by yourself and create pull request

**Comment by SpectralDragon** [comment]
> You may give it a try by yourself and create pull request

OK, I'll try

**Comment by ivlevAstef** [comment]
In future version fully remove UI folder.

Motivation:
* apple is moving away from storyboards.
* Support UI folder on SPM need make multiple targets.
* Many programmers have already switched to SwiftUI
* Cocoapods deprecated, and after two years, it will stop updating repositories. 

This task closed.
