### ISSUE TITLE
Множественные одинаковые register

### ISSUE THREAD

**Issue by VasilyKrainov** [ivlevAstef/DITranquillity#163]
При наличии нескольких одинаковых `register` `resolve` падает с критической ошибкой:
```
protocol P {
}

class C: P {
}

container.register(C.init).as(P.self).lifetime(.single) // 1
container.register(C.init).as(P.self).lifetime(.single) // 2
let obj: C = container.resolve() // crash
```
Ситуация довольно типовая, когда выражения 1 и 2 находятся в разных модулях. `lifetime` ситуацию не меняет.

**Comment by ivlevAstef** [comment]
Здравствуйте. Да такое не разрешено (в любой библиотеке, где-то просто это не пишется как ошибка, а просто игнорирует одну из регистраций), по как по мне понятным
причинам - зачем регистрировать в один контейнер одинаковые зависимости?
А если вы в одном месте решите слегка изменить её (тотже lifetime разный сделать), то какую зависимости нужно брать? 

Да и простой пример - вы же класс один и тот же в разных модулях почему-то не создаёте.

Регистрация зависимости должна быть в модуле где эта зависимость создана, а не где планируется использоваться.

**Comment by VasilyKrainov** [comment]
мысль понял, спасибо за разъяснение.  Попробую реструктурировать приложение, чтоб была одна регистрация
